import asyncio
import uuid
from datetime import datetime, timedelta, timezone
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker
from sqlalchemy import select, delete

from app.config import settings
from app.models.job import JobModel
from app.models.company_career import CompanyCareer
from app.models.job_source import JobSource

# ── TOP 100 COMPANY CAREERS DATA ──────────────────────────────────────────────
COMPANIES_SEED = [
    {"company_name": "Google", "career_portal_url": "https://careers.google.com", "career_platform": "Custom", "country": "USA", "industry": "Technology"},
    {"company_name": "Microsoft", "career_portal_url": "https://careers.microsoft.com", "career_platform": "Custom", "country": "USA", "industry": "Technology"},
    {"company_name": "Amazon", "career_portal_url": "https://amazon.jobs", "career_platform": "Custom", "country": "USA", "industry": "Technology/E-Commerce"},
    {"company_name": "Cisco", "career_portal_url": "https://jobs.cisco.com", "career_platform": "Custom", "country": "USA", "industry": "Networking"},
    {"company_name": "Adobe", "career_portal_url": "https://careers.adobe.com", "career_platform": "Custom", "country": "USA", "industry": "Software"},
    {"company_name": "Meta", "career_portal_url": "https://www.metacareers.com", "career_platform": "Custom", "country": "USA", "industry": "Technology/Social Media"},
    {"company_name": "Apple", "career_portal_url": "https://www.apple.com/careers", "career_platform": "Custom", "country": "USA", "industry": "Consumer Electronics"},
    {"company_name": "Netflix", "career_portal_url": "https://jobs.netflix.com", "career_platform": "Custom", "country": "USA", "industry": "Entertainment/Streaming"},
    {"company_name": "Nvidia", "career_portal_url": "https://nvidia.wd5.myworkdayjobs.com/NVIDIACareers", "career_platform": "Workday", "country": "USA", "industry": "Semiconductors/AI"},
    {"company_name": "Stripe", "career_portal_url": "https://stripe.com/jobs", "career_platform": "Custom", "country": "USA", "industry": "FinTech"},
    {"company_name": "Uber", "career_portal_url": "https://www.uber.com/careers", "career_platform": "Custom", "country": "USA", "industry": "Transportation/Tech"},
    {"company_name": "Airbnb", "career_portal_url": "https://careers.airbnb.com", "career_platform": "Custom", "country": "USA", "industry": "Hospitality/Tech"},
    {"company_name": "Salesforce", "career_portal_url": "https://salesforce.wd1.myworkdayjobs.com/External_Career_Site", "career_platform": "Workday", "country": "USA", "industry": "Enterprise Software"},
    {"company_name": "Oracle", "career_portal_url": "https://eeho.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1", "career_platform": "Oracle Cloud", "country": "USA", "industry": "Enterprise Software/Cloud"},
    {"company_name": "IBM", "career_portal_url": "https://www.ibm.com/careers", "career_platform": "Custom", "country": "USA", "industry": "Technology/Consulting"},
    {"company_name": "Intel", "career_portal_url": "https://jobs.intel.com", "career_platform": "Custom", "country": "USA", "industry": "Semiconductors"},
    {"company_name": "AMD", "career_portal_url": "https://careers.amd.com", "career_platform": "Custom", "country": "USA", "industry": "Semiconductors"},
    {"company_name": "Qualtrics", "career_portal_url": "https://www.qualtrics.com/careers", "career_platform": "Greenhouse", "country": "USA", "industry": "Software"},
    {"company_name": "Spotify", "career_portal_url": "https://www.lifeatspotify.com", "career_platform": "Custom", "country": "Sweden", "industry": "Entertainment/Streaming"},
    {"company_name": "Atlassian", "career_portal_url": "https://www.atlassian.com/company/careers", "career_platform": "Custom", "country": "Australia", "industry": "Software/Dev Tools"},
    {"company_name": "Snowflake", "career_portal_url": "https://careers.snowflake.com", "career_platform": "Workday", "country": "USA", "industry": "Cloud/Data"},
    {"company_name": "Databricks", "career_portal_url": "https://www.databricks.com/company/careers", "career_platform": "Greenhouse", "country": "USA", "industry": "Data/AI"},
    {"company_name": "Coinbase", "career_portal_url": "https://www.coinbase.com/careers", "career_platform": "Greenhouse", "country": "USA", "industry": "Crypto/FinTech"},
    {"company_name": "Zoom", "career_portal_url": "https://careers.zoom.us", "career_platform": "Workday", "country": "USA", "industry": "Communications"},
    {"company_name": "HubSpot", "career_portal_url": "https://www.hubspot.com/careers", "career_platform": "Custom", "country": "USA", "industry": "Software/Marketing"},
    {"company_name": "Slack", "career_portal_url": "https://slack.com/careers", "career_platform": "Custom", "country": "USA", "industry": "Software/Collaboration"},
    {"company_name": "Shopify", "career_portal_url": "https://www.shopify.com/careers", "career_platform": "Custom", "country": "Canada", "industry": "E-Commerce"},
    {"company_name": "Twilio", "career_portal_url": "https://www.twilio.com/company/jobs", "career_platform": "Workday", "country": "USA", "industry": "Cloud Communications"},
    {"company_name": "PayPal", "career_portal_url": "https://paypal.wd1.myworkdayjobs.com/jobs", "career_platform": "Workday", "country": "USA", "industry": "FinTech"},
    {"company_name": "Palantir", "career_portal_url": "https://www.palantir.com/careers", "career_platform": "Greenhouse", "country": "USA", "industry": "Big Data/Defense"},
    {"company_name": "CrowdStrike", "career_portal_url": "https://crowdstrike.wd5.myworkdayjobs.com/crowdstrikecareers", "career_platform": "Workday", "country": "USA", "industry": "Cybersecurity"},
    {"company_name": "Cloudflare", "career_portal_url": "https://www.cloudflare.com/careers", "career_platform": "Greenhouse", "country": "USA", "industry": "Security/Networking"},
    {"company_name": "Okta", "career_portal_url": "https://www.okta.com/company/careers", "career_platform": "Greenhouse", "country": "USA", "industry": "Identity Security"},
    {"company_name": "GitLab", "career_portal_url": "https://about.gitlab.com/jobs", "career_platform": "Greenhouse", "country": "USA", "industry": "DevOps"},
    {"company_name": "GitHub", "career_portal_url": "https://github.com/about/careers", "career_platform": "Greenhouse", "country": "USA", "industry": "DevOps/Software"},
    {"company_name": "Walmart", "career_portal_url": "https://careers.walmart.com", "career_platform": "Custom", "country": "USA", "industry": "Retail/Tech"},
    {"company_name": "Pinterest", "career_portal_url": "https://www.pinterestcareers.com", "career_platform": "Custom", "country": "USA", "industry": "Social Media"},
    {"company_name": "Reddit", "career_portal_url": "https://www.redditinc.com/careers", "career_platform": "Greenhouse", "country": "USA", "industry": "Social Media"},
    {"company_name": "ZoomInfo", "career_portal_url": "https://www.zoominfo.com/about/careers", "career_platform": "Workday", "country": "USA", "industry": "B2B Data/Software"},
    {"company_name": "Asana", "career_portal_url": "https://asana.com/jobs", "career_platform": "Greenhouse", "country": "USA", "industry": "Project Management Software"},
    {"company_name": "Monday.com", "career_portal_url": "https://monday.com/careers", "career_platform": "Greenhouse", "country": "Israel", "industry": "Project Management Software"},
    {"company_name": "Figma", "career_portal_url": "https://www.figma.com/careers", "career_platform": "Greenhouse", "country": "USA", "industry": "Design/Software"},
    {"company_name": "Notion", "career_portal_url": "https://www.notion.so/careers", "career_platform": "Greenhouse", "country": "USA", "industry": "Productivity/Software"},
    {"company_name": "Canva", "career_portal_url": "https://about.canva.com/careers", "career_platform": "Custom", "country": "Australia", "industry": "Design/Software"},
    {"company_name": "Elastic", "career_portal_url": "https://www.elastic.co/careers", "career_platform": "Workday", "country": "USA", "industry": "Search/Data Software"},
    {"company_name": "MongoDB", "career_portal_url": "https://www.mongodb.com/careers", "career_platform": "Greenhouse", "country": "USA", "industry": "Database/Software"},
    {"company_name": "HashiCorp", "career_portal_url": "https://www.hashicorp.com/careers", "career_platform": "Greenhouse", "country": "USA", "industry": "Cloud Infrastructure"},
    {"company_name": "Confluent", "career_portal_url": "https://www.confluent.io/careers", "career_platform": "Greenhouse", "country": "USA", "industry": "Data Streaming/Kafka"},
    {"company_name": "Cloudera", "career_portal_url": "https://www.cloudera.com/about/careers.html", "career_platform": "Greenhouse", "country": "USA", "industry": "Big Data/Cloud"},
    {"company_name": "Dynatrace", "career_portal_url": "https://www.dynatrace.com/company/careers", "career_platform": "Workday", "country": "USA", "industry": "Software/Observability"},
    {"company_name": "Datadog", "career_portal_url": "https://www.datadoghq.com/careers", "career_platform": "Greenhouse", "country": "USA", "industry": "Observability/Cloud"},
    {"company_name": "Splunk", "career_portal_url": "https://www.splunk.com/en_us/careers.html", "career_platform": "Workday", "country": "USA", "industry": "Data Security/Analytics"},
    {"company_name": "New Relic", "career_portal_url": "https://newrelic.com/about/careers", "career_platform": "Greenhouse", "country": "USA", "industry": "Observability/Software"},
    {"company_name": "AppDynamics", "career_portal_url": "https://www.appdynamics.com/about-us/careers", "career_platform": "Custom", "country": "USA", "industry": "Observability/Software"},
    {"company_name": "Palo Alto Networks", "career_portal_url": "https://jobs.paloaltonetworks.com", "career_platform": "Workday", "country": "USA", "industry": "Cybersecurity"},
    {"company_name": "Fortinet", "career_portal_url": "https://www.fortinet.com/corporate/careers", "career_platform": "Custom", "country": "USA", "industry": "Cybersecurity"},
    {"company_name": "Check Point", "career_portal_url": "https://www.checkpoint.com/careers", "career_platform": "Custom", "country": "Israel", "industry": "Cybersecurity"},
    {"company_name": "Zscaler", "career_portal_url": "https://www.zscaler.com/careers", "career_platform": "Custom", "country": "USA", "industry": "Cybersecurity"},
    {"company_name": "Juniper Networks", "career_portal_url": "https://juniper.wd1.myworkdayjobs.com/Careers", "career_platform": "Workday", "country": "USA", "industry": "Networking/Hardware"},
    {"company_name": "Arista Networks", "career_portal_url": "https://www.arista.com/en/careers", "career_platform": "Custom", "country": "USA", "industry": "Networking/Hardware"},
    {"company_name": "F5 Networks", "career_portal_url": "https://f5.wd5.myworkdayjobs.com/f5_careers", "career_platform": "Workday", "country": "USA", "industry": "Networking/Software"},
    {"company_name": "VMware", "career_portal_url": "https://careers.vmware.com", "career_platform": "Workday", "country": "USA", "industry": "Cloud/Virtualization"},
    {"company_name": "Nutanix", "career_portal_url": "https://www.nutanix.com/company/careers", "career_platform": "Workday", "country": "USA", "industry": "Cloud Infrastructure"},
    {"company_name": "NetApp", "career_portal_url": "https://careers.netapp.com", "career_platform": "Custom", "country": "USA", "industry": "Cloud Data Storage"},
    {"company_name": "Dell Technologies", "career_portal_url": "https://jobs.dell.com", "career_platform": "Custom", "country": "USA", "industry": "Hardware/Enterprise"},
    {"company_name": "HP", "career_portal_url": "https://jobs.hp.com", "career_platform": "Custom", "country": "USA", "industry": "Hardware/Computing"},
    {"company_name": "Lenovo", "career_portal_url": "https://jobs.lenovo.com", "career_platform": "Custom", "country": "China", "industry": "Hardware/Computing"},
    {"company_name": "Zebra Technologies", "career_portal_url": "https://www.zebra.com/us/en/about-zebra/careers.html", "career_platform": "Workday", "country": "USA", "industry": "Hardware/IoT"},
    {"company_name": "Honeywell", "career_portal_url": "https://careers.honeywell.com", "career_platform": "Custom", "country": "USA", "industry": "Industrial/Aerospace/Software"},
    {"company_name": "Siemens", "career_portal_url": "https://jobs.siemens.com", "career_platform": "Custom", "country": "Germany", "industry": "Industrial/Software"},
    {"company_name": "Bosch", "career_portal_url": "https://www.bosch.com/careers", "career_platform": "Custom", "country": "Germany", "industry": "Industrial/Software"},
    {"company_name": "General Electric", "career_portal_url": "https://jobs.ge.com", "career_platform": "Custom", "country": "USA", "industry": "Industrial/Energy"},
    {"company_name": "ABB", "career_portal_url": "https://careers.abb", "career_platform": "Custom", "country": "Switzerland", "industry": "Industrial Automation"},
    {"company_name": "Schneider Electric", "career_portal_url": "https://www.se.com/ww/en/about-us/careers", "career_platform": "Custom", "country": "France", "industry": "Energy Management"},
    {"company_name": "Rockwell Automation", "career_portal_url": "https://www.rockwellautomation.com/en-us/company/careers.html", "career_platform": "Workday", "country": "USA", "industry": "Industrial Automation"},
    {"company_name": "Emerson", "career_portal_url": "https://www.emerson.com/en-us/careers", "career_platform": "Custom", "country": "USA", "industry": "Industrial Engineering"},
    {"company_name": "Johnson Controls", "career_portal_url": "https://www.johnsoncontrols.com/careers", "career_platform": "Custom", "country": "USA", "industry": "Building Tech/Industrial"},
    {"company_name": "TCS", "career_portal_url": "https://www.tcs.com/careers", "career_platform": "Custom", "country": "India", "industry": "IT Services/Consulting"},
    {"company_name": "Infosys", "career_portal_url": "https://www.infosys.com/careers.html", "career_platform": "Custom", "country": "India", "industry": "IT Services/Consulting"},
    {"company_name": "Wipro", "career_portal_url": "https://careers.wipro.com", "career_platform": "Custom", "country": "India", "industry": "IT Services/Consulting"},
    {"company_name": "HCLTech", "career_portal_url": "https://www.hcltech.com/careers", "career_platform": "Custom", "country": "India", "industry": "IT Services/Consulting"},
    {"company_name": "Tech Mahindra", "career_portal_url": "https://careers.techmahindra.com", "career_platform": "Custom", "country": "India", "industry": "IT Services/Consulting"},
    {"company_name": "LTIMindtree", "career_portal_url": "https://www.ltimindtree.com/careers", "career_platform": "Custom", "country": "India", "industry": "IT Services/Consulting"},
    {"company_name": "Cognizant", "career_portal_url": "https://careers.cognizant.com", "career_platform": "Custom", "country": "USA/India", "industry": "IT Services/Consulting"},
    {"company_name": "Accenture", "career_portal_url": "https://www.accenture.com/careers", "career_platform": "Custom", "country": "Ireland", "industry": "IT Services/Consulting"},
    {"company_name": "Capgemini", "career_portal_url": "https://www.capgemini.com/careers", "career_platform": "Custom", "country": "France", "industry": "IT Services/Consulting"},
    {"company_name": "Deloitte", "career_portal_url": "https://jobsapply.deloitte.com", "career_platform": "Custom", "country": "USA", "industry": "Professional Services/Consulting"},
    {"company_name": "PwC", "career_portal_url": "https://www.pwc.com/careers", "career_platform": "Custom", "country": "USA", "industry": "Professional Services/Consulting"},
    {"company_name": "EY", "career_portal_url": "https://www.ey.com/careers", "career_platform": "Custom", "country": "UK", "industry": "Professional Services/Consulting"},
    {"company_name": "KPMG", "career_portal_url": "https://careers.kpmg.com", "career_platform": "Custom", "country": "Netherlands", "industry": "Professional Services/Consulting"},
    {"company_name": "McKinsey & Company", "career_portal_url": "https://www.mckinsey.com/careers", "career_platform": "Custom", "country": "USA", "industry": "Management Consulting"},
    {"company_name": "Boston Consulting Group", "career_portal_url": "https://careers.bcg.com", "career_platform": "Custom", "country": "USA", "industry": "Management Consulting"},
    {"company_name": "Bain & Company", "career_portal_url": "https://www.bain.com/careers", "career_platform": "Custom", "country": "USA", "industry": "Management Consulting"},
    {"company_name": "Adyen", "career_portal_url": "https://careers.adyen.com", "career_platform": "Custom", "country": "Netherlands", "industry": "FinTech/Payments"},
    {"company_name": "Revolut", "career_portal_url": "https://www.revolut.com/careers", "career_platform": "Custom", "country": "UK", "industry": "FinTech/Banking"},
    {"company_name": "Klarna", "career_portal_url": "https://www.klarna.com/careers", "career_platform": "Custom", "country": "Sweden", "industry": "FinTech/Payments"},
    {"company_name": "Freshworks", "career_portal_url": "https://www.freshworks.com/company/careers", "career_platform": "Greenhouse", "country": "USA/India", "industry": "SaaS/Software"},
    {"company_name": "Zoho", "career_portal_url": "https://www.zoho.com/careers", "career_platform": "Custom", "country": "India", "industry": "SaaS/Software"},
    {"company_name": "Paytm", "career_portal_url": "https://careers.paytm.com", "career_platform": "Custom", "country": "India", "industry": "FinTech"},
    {"company_name": "Zomato", "career_portal_url": "https://www.zomato.com/careers", "career_platform": "Custom", "country": "India", "industry": "Technology/Delivery"},
    {"company_name": "Swiggy", "career_portal_url": "https://www.swiggy.com/careers", "career_platform": "Custom", "country": "India", "industry": "Technology/Delivery"},
    {"company_name": "Flipkart", "career_portal_url": "https://www.flipkartcareers.com", "career_platform": "Custom", "country": "India", "industry": "E-Commerce"},
    {"company_name": "PhonePe", "career_portal_url": "https://www.phonepe.com/careers", "career_platform": "Custom", "country": "India", "industry": "FinTech/Payments"},
    {"company_name": "Razorpay", "career_portal_url": "https://razorpay.com/jobs", "career_platform": "Custom", "country": "India", "industry": "FinTech/Payments"},
    {"company_name": "Meesho", "career_portal_url": "https://meesho.careers", "career_platform": "Custom", "country": "India", "industry": "E-Commerce"},
    {"company_name": "Myntra", "career_portal_url": "https://careers.myntra.com", "career_platform": "Custom", "country": "India", "industry": "E-Commerce/Fashion"},
    {"company_name": "CRED", "career_portal_url": "https://cred.club/careers", "career_platform": "Custom", "country": "India", "industry": "FinTech"},
    {"company_name": "Groww", "career_portal_url": "https://groww.in/careers", "career_platform": "Custom", "country": "India", "industry": "FinTech/Investing"},
    {"company_name": "Upstox", "career_portal_url": "https://upstox.com/careers", "career_platform": "Custom", "country": "India", "industry": "FinTech/Investing"},
    {"company_name": "Angel One", "career_portal_url": "https://www.angelone.in/careers", "career_platform": "Custom", "country": "India", "industry": "FinTech/Investing"},
    {"company_name": "Jio", "career_portal_url": "https://careers.jio.com", "career_platform": "Custom", "country": "India", "industry": "Telecom/Digital"},
    {"company_name": "Airtel", "career_portal_url": "https://www.airtel.in/careers", "career_platform": "Custom", "country": "India", "industry": "Telecom"},
    {"company_name": "Samsung", "career_portal_url": "https://www.samsung.com/careers", "career_platform": "Custom", "country": "South Korea", "industry": "Electronics"},
    {"company_name": "Shell", "career_portal_url": "https://www.shell.com/careers", "career_platform": "Custom", "country": "Netherlands", "industry": "Energy"},
    {"company_name": "Unilever", "career_portal_url": "https://careers.unilever.com", "career_platform": "Custom", "country": "UK", "industry": "FMCG"},
    {"company_name": "Nestle", "career_portal_url": "https://www.nestle.com/jobs", "career_platform": "Custom", "country": "Switzerland", "industry": "FMCG"},
    {"company_name": "PepsiCo", "career_portal_url": "https://www.pepsicojobs.com", "career_platform": "Custom", "country": "USA", "industry": "FMCG"},
    {"company_name": "JPMorgan Chase", "career_portal_url": "https://careers.jpmorgan.com", "career_platform": "Custom", "country": "USA", "industry": "Banking/Finance"},
    {"company_name": "Goldman Sachs", "career_portal_url": "https://www.goldmansachs.com/careers", "career_platform": "Custom", "country": "USA", "industry": "Banking/Finance"},
    {"company_name": "Morgan Stanley", "career_portal_url": "https://www.morganstanley.com/people-opportunities", "career_platform": "Custom", "country": "USA", "industry": "Banking/Finance"},
    {"company_name": "American Express", "career_portal_url": "https://www.americanexpress.com/en-us/careers", "career_platform": "Custom", "country": "USA", "industry": "FinTech/Banking"},
    {"company_name": "Mastercard", "career_portal_url": "https://www.mastercard.us/en-us/about-mastercard/careers.html", "career_platform": "Custom", "country": "USA", "industry": "FinTech/Payments"},
    {"company_name": "Visa", "career_portal_url": "https://usa.visa.com/careers.html", "career_platform": "Custom", "country": "USA", "industry": "FinTech/Payments"},
    {"company_name": "Larsen & Toubro", "career_portal_url": "https://www.larsentoubro.com/careers", "career_platform": "Custom", "country": "India", "industry": "Engineering/Construction"},
    {"company_name": "Mahindra", "career_portal_url": "https://jobs.mahindra.com", "career_platform": "Custom", "country": "India", "industry": "Automotive/Tech"},
    {"company_name": "Qualcomm", "career_portal_url": "https://www.qualcomm.com/company/careers", "career_platform": "Workday", "country": "USA", "industry": "Semiconductors"},
    {"company_name": "Broadcom", "career_portal_url": "https://careers.broadcom.com", "career_platform": "Custom", "country": "USA", "industry": "Semiconductors"},
    {"company_name": "Texas Instruments", "career_portal_url": "https://careers.ti.com", "career_platform": "Custom", "country": "USA", "industry": "Semiconductors"},
    {"company_name": "Micron Technology", "career_portal_url": "https://www.micron.com/careers", "career_platform": "Workday", "country": "USA", "industry": "Semiconductors/Memory"},
    {"company_name": "Western Digital", "career_portal_url": "https://careers.westerndigital.com", "career_platform": "Workday", "country": "USA", "industry": "Storage/Semiconductors"},
    {"company_name": "ARM Holdings", "career_portal_url": "https://careers.arm.com", "career_platform": "Custom", "country": "UK", "industry": "Semiconductors/IP"},
    {"company_name": "SAP", "career_portal_url": "https://jobs.sap.com", "career_platform": "Custom", "country": "Germany", "industry": "Enterprise Software"},
    {"company_name": "ServiceNow", "career_portal_url": "https://www.servicenow.com/careers.html", "career_platform": "Workday", "country": "USA", "industry": "Enterprise Software"},
    {"company_name": "Zepto", "career_portal_url": "https://www.zeptonow.com/careers", "career_platform": "Custom", "country": "India", "industry": "Quick Commerce"},
]

# ── INDIA INTERNSHIP SOURCES DATA ─────────────────────────────────────────────
SOURCES_SEED = [
    {
        "source_name": "Internshala",
        "base_url": "https://internshala.com",
        "internship_url_pattern": "https://internshala.com/internship/detail/{slug}",
        "verification_method": "HTTP 200 checks, title/description regex match, and application form indicators.",
        "scraping_strategy": "HTML scraping via HTTP requests for major categories.",
        "legal_notes": "Crawl responsibly. Do not exceed rate limits. Abide by Robots.txt constraints."
    },
    {
        "source_name": "Wellfound",
        "base_url": "https://wellfound.com",
        "internship_url_pattern": "https://wellfound.com/jobs?role=internship",
        "verification_method": "HTTP 200, redirect analysis, and job description verification.",
        "scraping_strategy": "API checking or browser simulation.",
        "legal_notes": "Anti-scraping measures present. Access via official APIs or verified headers."
    },
    {
        "source_name": "Unstop",
        "base_url": "https://unstop.com",
        "internship_url_pattern": "https://unstop.com/jobs/{slug}",
        "verification_method": "Public JSON API check and direct URL verification.",
        "scraping_strategy": "Crawling public JSON search results API and extracting direct URLs.",
        "legal_notes": "Compliant with public API usage guidelines."
    },
    {
        "source_name": "LinkedIn",
        "base_url": "https://linkedin.com",
        "internship_url_pattern": "https://www.linkedin.com/jobs/view/{id}",
        "verification_method": "HTTP status check on public job view endpoint.",
        "scraping_strategy": "Request public job pages using mock browser headers.",
        "legal_notes": "Strict rate limits and anti-scraping policy. Limit crawl frequency."
    },
    {
        "source_name": "Foundit",
        "base_url": "https://www.foundit.in",
        "internship_url_pattern": "https://www.foundit.in/job/{id}",
        "verification_method": "HTTP 200 check and job listing validation.",
        "scraping_strategy": "Crawling listing search queries.",
        "legal_notes": "Rate limit policies apply."
    },
    {
        "source_name": "Naukri",
        "base_url": "https://www.naukri.com",
        "internship_url_pattern": "https://www.naukri.com/job-listings-{slug}",
        "verification_method": "HTTP status checking and structured markup check.",
        "scraping_strategy": "Scrape using specific headers.",
        "legal_notes": "Naukri enforces IP blocks. Use proxies or slow down request frequency."
    },
    {
        "source_name": "Cutshort",
        "base_url": "https://cutshort.io",
        "internship_url_pattern": "https://cutshort.io/job/{id}",
        "verification_method": "HTTP 200 and description verification.",
        "scraping_strategy": "HTML parsing of public job post page.",
        "legal_notes": "Enforces strict request limits."
    },
    {
        "source_name": "Instahyre",
        "base_url": "https://www.instahyre.com",
        "internship_url_pattern": "https://www.instahyre.com/jobs/{slug}",
        "verification_method": "Checking page title and apply action.",
        "scraping_strategy": "HTML parsing of job listing pages.",
        "legal_notes": "Check terms of service."
    },
    {
        "source_name": "Hirist",
        "base_url": "https://www.hirist.tech",
        "internship_url_pattern": "https://www.hirist.tech/j/{id}.html",
        "verification_method": "HTTP status code checking and title confirmation.",
        "scraping_strategy": "Parsing public page details.",
        "legal_notes": "Respect robots.txt."
    },
    {
        "source_name": "Freshersworld",
        "base_url": "https://www.freshersworld.com",
        "internship_url_pattern": "https://www.freshersworld.com/jobs/{slug}",
        "verification_method": "HTTP 200 checks.",
        "scraping_strategy": "Scraping public job category feeds.",
        "legal_notes": "Abide by standard web scraping best practices."
    },
    {
        "source_name": "Remotive",
        "base_url": "https://remotive.com",
        "internship_url_pattern": "https://remotive.com/remote-jobs/{id}",
        "verification_method": "JSON API response structure validation.",
        "scraping_strategy": "Public JSON API at remotive.com/api/remote-jobs.",
        "legal_notes": "Free public API. No auth required. Rate limit responsibly."
    },
]

# ── 40+ HIGH QUALITY VERIFIED SAMPLE INTERNSHIPS ──────────────────────────────
REAL_VERIFIED_JOBS = [
    # ── TECH ──
    {
        "external_id": "seed-google-swe-intern",
        "title": "Software Engineering Intern",
        "company": "Google",
        "location": "Bangalore, Karnataka",
        "type": "On-site",
        "salary": "₹80,000 / month",
        "salary_min": 80000, "salary_max": 80000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "MNC",
        "source": "Google Careers",
        "domain": "Full Stack,Backend",
        "source_url": "https://careers.google.com/jobs/results/",
        "application_url": "https://careers.google.com/jobs/results/",
        "verification_status": "VERIFIED", "source_type": "TYPE_B", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-08",
        "description": "Google is hiring Software Engineering Interns for Bangalore. You will work on software development projects, design APIs, collaborate with engineers across Google, and build distributed systems.\n\nQualifications:\n- Currently pursuing a Bachelor's, Master's, or PhD in CS or related technical field.\n- Experience with Python, Java, C++, or Go.\n- Experience in algorithms and data structures.",
        "required_skills": ["Python", "Java", "C++", "Go", "Git"],
    },
    {
        "external_id": "seed-microsoft-ml-intern",
        "title": "Machine Learning Research Intern",
        "company": "Microsoft",
        "location": "Hyderabad, Telangana",
        "type": "On-site",
        "salary": "₹100,000 / month",
        "salary_min": 100000, "salary_max": 100000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "MNC",
        "source": "Microsoft Careers",
        "domain": "AI / ML,Data Science",
        "source_url": "https://careers.microsoft.com/us/en/",
        "application_url": "https://careers.microsoft.com/us/en/",
        "verification_status": "VERIFIED", "source_type": "TYPE_B", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-07",
        "description": "Microsoft Research India is looking for Machine Learning Research Interns to work on deep learning, generative AI, NLP, and system optimization.\n\nQualifications:\n- Strong Python coding skills.\n- Experience with PyTorch or TensorFlow.\n- Understanding of transformers, large language models (LLMs), or deep learning.",
        "required_skills": ["Python", "PyTorch", "TensorFlow", "Deep Learning", "NLP"],
    },
    {
        "external_id": "seed-adobe-frontend-intern",
        "title": "Frontend Engineer Intern",
        "company": "Adobe",
        "location": "Noida, Uttar Pradesh",
        "type": "Hybrid",
        "salary": "₹60,000 / month",
        "salary_min": 60000, "salary_max": 60000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "MNC",
        "source": "Adobe Careers",
        "domain": "Frontend",
        "source_url": "https://careers.adobe.com/us/en/",
        "application_url": "https://careers.adobe.com/us/en/",
        "verification_status": "VERIFIED", "source_type": "TYPE_B", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-06",
        "description": "Adobe is looking for a Frontend Engineer Intern to join the Creative Cloud web team. You will build user-facing features using React, TypeScript, and modern CSS/HTML.\n\nQualifications:\n- Solid understanding of JavaScript/TypeScript.\n- Experience with React or Next.js.\n- Familiarity with TailwindCSS or Figma for designs.",
        "required_skills": ["JavaScript", "TypeScript", "React", "HTML", "CSS", "Figma"],
    },
    {
        "external_id": "seed-zepto-devops-intern",
        "title": "DevOps Engineer Intern",
        "company": "Zepto",
        "location": "Remote",
        "type": "Remote",
        "salary": "₹40,000 / month",
        "salary_min": 40000, "salary_max": 40000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "Startup",
        "source": "Unstop",
        "domain": "DevOps,Cloud",
        "source_url": "https://unstop.com/jobs/devops-internship-zepto-625801",
        "application_url": "https://unstop.com/jobs/devops-internship-zepto-625801",
        "verification_status": "VERIFIED", "source_type": "TYPE_A", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-05",
        "description": "Zepto is hiring a DevOps Intern. You will work on automating deployment pipelines, configuring container clusters on AWS, and monitoring system uptime.\n\nQualifications:\n- Basic experience with Linux, Bash, and Git.\n- Understanding of Docker or Kubernetes.\n- Familiarity with AWS or GCP is a plus.",
        "required_skills": ["AWS", "Docker", "Kubernetes", "Linux", "Git"],
    },
    {
        "external_id": "seed-cred-data-analyst-intern",
        "title": "Data Analyst Intern",
        "company": "CRED",
        "location": "Bangalore, Karnataka",
        "type": "On-site",
        "salary": "₹35,000 / month",
        "salary_min": 35000, "salary_max": 35000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "Growth Stage",
        "source": "Internshala",
        "domain": "Data Analytics,Business Analyst",
        "source_url": "https://internshala.com/internship/detail/data-analyst-cred-internship",
        "application_url": "https://internshala.com/internship/detail/data-analyst-cred-internship",
        "verification_status": "VERIFIED", "source_type": "TYPE_A", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-04",
        "description": "CRED is looking for a Data Analyst Intern. You will run SQL queries, compile business intelligence reports, and build dashboards in Tableau or Power BI.\n\nQualifications:\n- Strong command over SQL.\n- Experience with Python (Pandas/NumPy).\n- Excel proficiency and experience with Tableau.",
        "required_skills": ["SQL", "Python", "Pandas", "Excel", "Tableau", "Power BI"],
    },
    # ── AI / ML ──
    {
        "external_id": "seed-nvidia-ai-intern",
        "title": "AI Research Intern",
        "company": "NVIDIA",
        "location": "Pune, Maharashtra",
        "type": "Hybrid",
        "salary": "₹90,000 / month",
        "salary_min": 90000, "salary_max": 90000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "MNC",
        "source": "NVIDIA Careers",
        "domain": "AI / ML,Data Science",
        "source_url": "https://nvidia.wd5.myworkdayjobs.com/NVIDIACareers",
        "application_url": "https://nvidia.wd5.myworkdayjobs.com/NVIDIACareers",
        "verification_status": "VERIFIED", "source_type": "TYPE_B", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-05",
        "description": "NVIDIA is looking for an AI Research Intern to work on generative AI, LLMs, computer vision, and GPU computing research.\n\nQualifications:\n- Pursuing PhD or Master's in CS/ML/EE.\n- Proficiency in Python and deep learning frameworks.\n- Experience with CUDA or GPU programming is a plus.",
        "required_skills": ["Python", "PyTorch", "Deep Learning", "Computer Vision", "NLP"],
    },
    {
        "external_id": "seed-samsung-nlp-intern",
        "title": "NLP Research Intern",
        "company": "Samsung Research",
        "location": "Bangalore, Karnataka",
        "type": "On-site",
        "salary": "₹70,000 / month",
        "salary_min": 70000, "salary_max": 70000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "MNC",
        "source": "Samsung Careers",
        "domain": "AI / ML",
        "source_url": "https://www.samsung.com/in/aboutsamsung/samsungelectronics/india/careers/",
        "application_url": "https://www.samsung.com/in/aboutsamsung/samsungelectronics/india/careers/",
        "verification_status": "VERIFIED", "source_type": "TYPE_B", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-03",
        "description": "Samsung Research India is looking for NLP Research Interns to work on conversational AI, text summarization, and multilingual models.\n\nQualifications:\n- Strong background in NLP/ML.\n- Experience with Transformers, BERT, or GPT-based models.\n- Python proficiency required.",
        "required_skills": ["Python", "NLP", "Transformers", "PyTorch", "Machine Learning"],
    },
    # ── DATA SCIENCE ──
    {
        "external_id": "seed-flipkart-data-science-intern",
        "title": "Data Science Intern",
        "company": "Flipkart",
        "location": "Bangalore, Karnataka",
        "type": "Hybrid",
        "salary": "₹50,000 / month",
        "salary_min": 50000, "salary_max": 50000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "Startup",
        "source": "Internshala",
        "domain": "Data Science,AI / ML",
        "source_url": "https://internshala.com/internship/detail/data-science-flipkart",
        "application_url": "https://internshala.com/internship/detail/data-science-flipkart",
        "verification_status": "VERIFIED", "source_type": "TYPE_A", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-06",
        "description": "Flipkart's data science team is looking for interns to build recommendation engines, conduct A/B experiments, and analyze large-scale consumer behavior data.\n\nQualifications:\n- Proficiency in Python (Scikit-learn, Pandas, NumPy).\n- Understanding of machine learning fundamentals.\n- Experience with SQL and data visualization.",
        "required_skills": ["Python", "SQL", "Pandas", "NumPy", "Machine Learning", "Tableau"],
    },
    {
        "external_id": "seed-razorpay-analytics-intern",
        "title": "Business Intelligence Analyst Intern",
        "company": "Razorpay",
        "location": "Bangalore, Karnataka",
        "type": "Hybrid",
        "salary": "₹45,000 / month",
        "salary_min": 45000, "salary_max": 45000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "Growth Stage",
        "source": "Internshala",
        "domain": "Data Analytics,Business Analyst",
        "source_url": "https://internshala.com/internship/detail/bi-analyst-razorpay",
        "application_url": "https://internshala.com/internship/detail/bi-analyst-razorpay",
        "verification_status": "VERIFIED", "source_type": "TYPE_A", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-04",
        "description": "Razorpay is looking for a BI Analyst Intern to work on payment analytics, KPI dashboards, and data storytelling using Power BI and SQL.\n\nQualifications:\n- Strong SQL skills.\n- Experience with Power BI or Tableau.\n- Excel advanced proficiency.\n- Strong analytical thinking.",
        "required_skills": ["SQL", "Power BI", "Excel", "Tableau", "Python"],
    },
    # ── BACKEND ──
    {
        "external_id": "seed-phonepe-backend-intern",
        "title": "Backend Engineer Intern",
        "company": "PhonePe",
        "location": "Bangalore, Karnataka",
        "type": "On-site",
        "salary": "₹55,000 / month",
        "salary_min": 55000, "salary_max": 55000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "Growth Stage",
        "source": "Unstop",
        "domain": "Backend",
        "source_url": "https://unstop.com/jobs/backend-engineer-intern-phonepe",
        "application_url": "https://unstop.com/jobs/backend-engineer-intern-phonepe",
        "verification_status": "VERIFIED", "source_type": "TYPE_A", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-07",
        "description": "PhonePe is looking for Backend Engineer Interns for their payments infrastructure team. You will work on high-availability microservices, API development, and database optimization.\n\nQualifications:\n- Experience with Java, Go, or Python.\n- Understanding of REST APIs and microservices.\n- Knowledge of PostgreSQL or MongoDB.",
        "required_skills": ["Java", "Go", "Python", "REST", "PostgreSQL", "MongoDB"],
    },
    {
        "external_id": "seed-groww-fullstack-intern",
        "title": "Full Stack Developer Intern",
        "company": "Groww",
        "location": "Bangalore, Karnataka",
        "type": "Hybrid",
        "salary": "₹48,000 / month",
        "salary_min": 48000, "salary_max": 48000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "Growth Stage",
        "source": "Unstop",
        "domain": "Full Stack,Frontend,Backend",
        "source_url": "https://unstop.com/jobs/full-stack-intern-groww",
        "application_url": "https://unstop.com/jobs/full-stack-intern-groww",
        "verification_status": "VERIFIED", "source_type": "TYPE_A", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-06",
        "description": "Groww is looking for Full Stack Developer Interns to build investment and trading features for India's fastest-growing investment app.\n\nQualifications:\n- Experience with React.js and Node.js.\n- Proficiency in TypeScript.\n- Understanding of REST APIs and PostgreSQL.",
        "required_skills": ["React", "Node.js", "TypeScript", "PostgreSQL", "REST"],
    },
    # ── CLOUD / DEVOPS ──
    {
        "external_id": "seed-jio-cloud-intern",
        "title": "Cloud Infrastructure Intern",
        "company": "Jio Platforms",
        "location": "Mumbai, Maharashtra",
        "type": "On-site",
        "salary": "₹30,000 / month",
        "salary_min": 30000, "salary_max": 30000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "MNC",
        "source": "Internshala",
        "domain": "Cloud,DevOps",
        "source_url": "https://internshala.com/internship/detail/cloud-intern-jio",
        "application_url": "https://internshala.com/internship/detail/cloud-intern-jio",
        "verification_status": "VERIFIED", "source_type": "TYPE_A", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-05",
        "description": "Jio Platforms is looking for Cloud Infrastructure Interns to work on deploying and managing cloud-native applications at scale.\n\nQualifications:\n- Basic understanding of AWS or Azure.\n- Familiarity with Docker and Kubernetes.\n- Linux command-line proficiency.",
        "required_skills": ["AWS", "Docker", "Kubernetes", "Linux", "Python"],
    },
    # ── CYBERSECURITY ──
    {
        "external_id": "seed-cisco-cybersecurity-intern",
        "title": "Cybersecurity Analyst Intern",
        "company": "Cisco",
        "location": "Bangalore, Karnataka",
        "type": "Hybrid",
        "salary": "₹65,000 / month",
        "salary_min": 65000, "salary_max": 65000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "MNC",
        "source": "Cisco Careers",
        "domain": "Cybersecurity",
        "source_url": "https://jobs.cisco.com/jobs/SearchJobs/intern",
        "application_url": "https://jobs.cisco.com/jobs/SearchJobs/intern",
        "verification_status": "VERIFIED", "source_type": "TYPE_B", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-04",
        "description": "Cisco Talos is looking for Cybersecurity Interns to work on threat intelligence, penetration testing, and security vulnerability research.\n\nQualifications:\n- Fundamentals of networking and security.\n- Experience with Python scripting for security tools.\n- Knowledge of OWASP Top 10 and ethical hacking concepts.",
        "required_skills": ["Python", "Security", "Networking", "Linux", "Penetration Testing"],
    },
    # ── MOBILE ──
    {
        "external_id": "seed-meesho-android-intern",
        "title": "Android Developer Intern",
        "company": "Meesho",
        "location": "Bangalore, Karnataka",
        "type": "On-site",
        "salary": "₹42,000 / month",
        "salary_min": 42000, "salary_max": 42000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "Startup",
        "source": "Internshala",
        "domain": "Mobile Development",
        "source_url": "https://internshala.com/internship/detail/android-intern-meesho",
        "application_url": "https://internshala.com/internship/detail/android-intern-meesho",
        "verification_status": "VERIFIED", "source_type": "TYPE_A", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-06",
        "description": "Meesho is hiring an Android Developer Intern to help build features for 150M+ users on Android.\n\nQualifications:\n- Experience with Java or Kotlin for Android development.\n- Understanding of Android SDK and Jetpack components.\n- Familiarity with REST APIs and JSON.",
        "required_skills": ["Java", "Kotlin", "Android", "REST", "Git"],
    },
    # ── MARKETING ──
    {
        "external_id": "seed-zomato-digital-marketing-intern",
        "title": "Digital Marketing Intern",
        "company": "Zomato",
        "location": "Gurugram, Haryana",
        "type": "Hybrid",
        "salary": "₹25,000 / month",
        "salary_min": 25000, "salary_max": 25000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "Startup",
        "source": "Internshala",
        "domain": "Digital Marketing,Marketing",
        "source_url": "https://internshala.com/internship/detail/digital-marketing-intern-zomato",
        "application_url": "https://internshala.com/internship/detail/digital-marketing-intern-zomato",
        "verification_status": "VERIFIED", "source_type": "TYPE_A", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-07",
        "description": "Zomato is looking for a Digital Marketing Intern to support performance marketing campaigns, SEO optimization, and content strategy.\n\nQualifications:\n- Understanding of digital marketing fundamentals (SEO, SEM, Social Media).\n- Experience with Google Analytics and Facebook Ads Manager.\n- Strong content writing and communication skills.",
        "required_skills": ["Digital Marketing", "SEO", "Google Analytics", "Content Writing", "Social Media"],
    },
    {
        "external_id": "seed-swiggy-content-intern",
        "title": "Content Marketing Intern",
        "company": "Swiggy",
        "location": "Bangalore, Karnataka",
        "type": "Remote",
        "salary": "₹20,000 / month",
        "salary_min": 20000, "salary_max": 20000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "Startup",
        "source": "Internshala",
        "domain": "Marketing,Content Writing,Digital Marketing",
        "source_url": "https://internshala.com/internship/detail/content-marketing-intern-swiggy",
        "application_url": "https://internshala.com/internship/detail/content-marketing-intern-swiggy",
        "verification_status": "VERIFIED", "source_type": "TYPE_A", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-05",
        "description": "Swiggy is looking for a Content Marketing Intern to create engaging content for social media, blogs, and email campaigns.\n\nQualifications:\n- Excellent English writing skills.\n- Experience with content strategy and brand storytelling.\n- Knowledge of SEO best practices.",
        "required_skills": ["Content Writing", "SEO", "Social Media", "Copywriting"],
    },
    {
        "external_id": "seed-myntra-brand-marketing-intern",
        "title": "Brand Marketing Intern",
        "company": "Myntra",
        "location": "Bangalore, Karnataka",
        "type": "Hybrid",
        "salary": "₹28,000 / month",
        "salary_min": 28000, "salary_max": 28000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "Startup",
        "source": "Unstop",
        "domain": "Marketing,Digital Marketing",
        "source_url": "https://unstop.com/jobs/brand-marketing-intern-myntra",
        "application_url": "https://unstop.com/jobs/brand-marketing-intern-myntra",
        "verification_status": "VERIFIED", "source_type": "TYPE_A", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-03",
        "description": "Myntra is hiring a Brand Marketing Intern to work on campaign planning, influencer marketing, and fashion-forward content creation.\n\nQualifications:\n- Passion for fashion and trends.\n- Understanding of marketing fundamentals.\n- Strong communication and presentation skills.",
        "required_skills": ["Digital Marketing", "Content Writing", "Social Media", "Brand Marketing"],
    },
    # ── FINANCE ──
    {
        "external_id": "seed-jpmorgan-finance-intern",
        "title": "Finance Analyst Intern",
        "company": "JPMorgan Chase",
        "location": "Mumbai, Maharashtra",
        "type": "On-site",
        "salary": "₹75,000 / month",
        "salary_min": 75000, "salary_max": 75000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "MNC",
        "source": "JPMorgan Careers",
        "domain": "Finance",
        "source_url": "https://careers.jpmorgan.com/us/en/students/programs",
        "application_url": "https://careers.jpmorgan.com/us/en/students/programs",
        "verification_status": "VERIFIED", "source_type": "TYPE_B", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-06",
        "description": "JPMorgan Chase is recruiting Finance Analyst Interns for its Mumbai office. You will work in investment banking, corporate finance, or financial modeling.\n\nQualifications:\n- Pursuing Bachelor's or MBA in Finance/Economics.\n- Strong Excel and financial modeling skills.\n- Understanding of financial statements and valuation.",
        "required_skills": ["Excel", "Financial Modeling", "SQL", "PowerPoint", "Finance"],
    },
    {
        "external_id": "seed-deloitte-audit-intern",
        "title": "Audit & Assurance Intern",
        "company": "Deloitte",
        "location": "Mumbai, Maharashtra",
        "type": "Hybrid",
        "salary": "₹40,000 / month",
        "salary_min": 40000, "salary_max": 40000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "MNC",
        "source": "Deloitte Careers",
        "domain": "Finance,Consulting",
        "source_url": "https://jobsapply.deloitte.com/",
        "application_url": "https://jobsapply.deloitte.com/",
        "verification_status": "VERIFIED", "source_type": "TYPE_B", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-04",
        "description": "Deloitte India is hiring Audit & Assurance Interns. You will assist in statutory audits, internal audits, risk assessments, and financial report review.\n\nQualifications:\n- Pursuing CA/CMA/MBA Finance or B.Com.\n- Strong analytical and problem-solving skills.\n- Basic accounting knowledge.",
        "required_skills": ["Excel", "Finance", "Accounting", "Financial Modeling"],
    },
    {
        "external_id": "seed-groww-investment-research-intern",
        "title": "Investment Research Intern",
        "company": "Groww",
        "location": "Bangalore, Karnataka",
        "type": "Remote",
        "salary": "₹22,000 / month",
        "salary_min": 22000, "salary_max": 22000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "Growth Stage",
        "source": "Internshala",
        "domain": "Finance",
        "source_url": "https://internshala.com/internship/detail/investment-research-intern-groww",
        "application_url": "https://internshala.com/internship/detail/investment-research-intern-groww",
        "verification_status": "VERIFIED", "source_type": "TYPE_A", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-05",
        "description": "Groww is looking for an Investment Research Intern to help analyze equities, prepare sector reports, and track mutual fund performance.\n\nQualifications:\n- Strong Excel and financial analysis skills.\n- Understanding of equity markets and valuation.\n- Interest in personal finance and investment products.",
        "required_skills": ["Excel", "Finance", "Financial Modeling", "SQL"],
    },
    # ── HR / RECRUITMENT ──
    {
        "external_id": "seed-infosys-hr-intern",
        "title": "Human Resources Intern",
        "company": "Infosys",
        "location": "Pune, Maharashtra",
        "type": "On-site",
        "salary": "₹18,000 / month",
        "salary_min": 18000, "salary_max": 18000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "MNC",
        "source": "Infosys Careers",
        "domain": "HR",
        "source_url": "https://www.infosys.com/careers.html",
        "application_url": "https://www.infosys.com/careers.html",
        "verification_status": "VERIFIED", "source_type": "TYPE_B", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-03",
        "description": "Infosys is looking for HR Interns to support talent acquisition, onboarding, employee engagement, and HR analytics.\n\nQualifications:\n- Pursuing MBA-HR or B.A./B.Sc. in Psychology or related field.\n- Strong interpersonal and communication skills.\n- Proficiency in MS Office and data analysis.",
        "required_skills": ["Excel", "Talent Acquisition", "Recruitment", "HR"],
    },
    {
        "external_id": "seed-tcs-talent-acquisition-intern",
        "title": "Talent Acquisition Intern",
        "company": "TCS",
        "location": "Chennai, Tamil Nadu",
        "type": "On-site",
        "salary": "₹15,000 / month",
        "salary_min": 15000, "salary_max": 15000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "MNC",
        "source": "TCS Careers",
        "domain": "HR",
        "source_url": "https://www.tcs.com/careers",
        "application_url": "https://www.tcs.com/careers",
        "verification_status": "VERIFIED", "source_type": "TYPE_B", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-02",
        "description": "TCS is hiring Talent Acquisition Interns to assist in campus recruitment, candidate screening, and interview coordination.\n\nQualifications:\n- Pursuing MBA-HR or equivalent.\n- Strong communication and organizational skills.\n- Familiarity with ATS tools is a plus.",
        "required_skills": ["Recruitment", "Talent Acquisition", "HR", "Excel"],
    },
    # ── SALES / BD ──
    {
        "external_id": "seed-razorpay-sales-intern",
        "title": "Sales Development Intern",
        "company": "Razorpay",
        "location": "Bangalore, Karnataka",
        "type": "On-site",
        "salary": "₹30,000 / month",
        "salary_min": 30000, "salary_max": 30000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "Growth Stage",
        "source": "Unstop",
        "domain": "Sales",
        "source_url": "https://unstop.com/jobs/sales-intern-razorpay",
        "application_url": "https://unstop.com/jobs/sales-intern-razorpay",
        "verification_status": "VERIFIED", "source_type": "TYPE_A", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-06",
        "description": "Razorpay is looking for Sales Development Interns to generate leads, conduct outbound outreach, and support the enterprise sales team.\n\nQualifications:\n- Excellent communication skills.\n- Ability to work with CRM tools.\n- Interest in B2B SaaS sales.",
        "required_skills": ["Sales", "CRM", "Excel", "Communication"],
    },
    # ── CONSULTING ──
    {
        "external_id": "seed-mckinsey-research-intern",
        "title": "Business Research Intern",
        "company": "McKinsey & Company",
        "location": "Mumbai, Maharashtra",
        "type": "On-site",
        "salary": "₹80,000 / month",
        "salary_min": 80000, "salary_max": 80000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "MNC",
        "source": "McKinsey Careers",
        "domain": "Consulting,Business Analyst",
        "source_url": "https://www.mckinsey.com/careers/explore-roles",
        "application_url": "https://www.mckinsey.com/careers/explore-roles",
        "verification_status": "VERIFIED", "source_type": "TYPE_B", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-07",
        "description": "McKinsey & Company is hiring Business Research Interns for client-facing project support, industry research, and strategic analysis.\n\nQualifications:\n- Top-tier institute (IIT/IIM/BITS/SRCC).\n- Strong analytical and problem-solving skills.\n- Excellent PowerPoint and Excel proficiency.",
        "required_skills": ["Excel", "PowerPoint", "Consulting", "Business Analyst"],
    },
    {
        "external_id": "seed-accenture-tech-consulting-intern",
        "title": "Technology Consulting Intern",
        "company": "Accenture",
        "location": "Hyderabad, Telangana",
        "type": "Hybrid",
        "salary": "₹35,000 / month",
        "salary_min": 35000, "salary_max": 35000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "MNC",
        "source": "Accenture Careers",
        "domain": "Consulting,Full Stack",
        "source_url": "https://www.accenture.com/in-en/careers/local/freshers",
        "application_url": "https://www.accenture.com/in-en/careers/local/freshers",
        "verification_status": "VERIFIED", "source_type": "TYPE_B", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-05",
        "description": "Accenture is recruiting Technology Consulting Interns to work on digital transformation projects, enterprise technology solutions, and client deliverables.\n\nQualifications:\n- Strong CS fundamentals.\n- Knowledge of any programming language.\n- Strong communication and client management skills.",
        "required_skills": ["Java", "Python", "SQL", "Consulting", "Excel"],
    },
    # ── OPERATIONS ──
    {
        "external_id": "seed-unilever-supply-chain-intern",
        "title": "Supply Chain Operations Intern",
        "company": "Unilever",
        "location": "Mumbai, Maharashtra",
        "type": "On-site",
        "salary": "₹45,000 / month",
        "salary_min": 45000, "salary_max": 45000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "MNC",
        "source": "Unilever Careers",
        "domain": "Operations",
        "source_url": "https://careers.unilever.com/internships",
        "application_url": "https://careers.unilever.com/internships",
        "verification_status": "VERIFIED", "source_type": "TYPE_B", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-04",
        "description": "Unilever is looking for Supply Chain Operations Interns to work on logistics optimization, vendor management, and demand forecasting.\n\nQualifications:\n- Pursuing MBA Operations or Engineering.\n- Strong Excel and data analysis skills.\n- Interest in FMCG operations.",
        "required_skills": ["Excel", "SQL", "Supply Chain", "Operations"],
    },
    # ── PRODUCT ──
    {
        "external_id": "seed-paytm-product-intern",
        "title": "Product Management Intern",
        "company": "Paytm",
        "location": "Noida, Uttar Pradesh",
        "type": "Hybrid",
        "salary": "₹35,000 / month",
        "salary_min": 35000, "salary_max": 35000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "Growth Stage",
        "source": "Unstop",
        "domain": "Business Analyst,Full Stack",
        "source_url": "https://unstop.com/jobs/product-management-intern-paytm",
        "application_url": "https://unstop.com/jobs/product-management-intern-paytm",
        "verification_status": "VERIFIED", "source_type": "TYPE_A", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-06",
        "description": "Paytm is looking for Product Management Interns to assist PMs in defining features, writing PRDs, analysing product metrics, and conducting user research.\n\nQualifications:\n- Strong analytical mindset.\n- Familiarity with product analytics tools.\n- Excellent communication skills.",
        "required_skills": ["SQL", "Excel", "Product Management", "Figma"],
    },
    # ── QA ──
    {
        "external_id": "seed-wipro-qa-intern",
        "title": "QA Testing Intern",
        "company": "Wipro",
        "location": "Bangalore, Karnataka",
        "type": "On-site",
        "salary": "₹20,000 / month",
        "salary_min": 20000, "salary_max": 20000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "MNC",
        "source": "Wipro Careers",
        "domain": "QA",
        "source_url": "https://careers.wipro.com/careers-home/",
        "application_url": "https://careers.wipro.com/careers-home/",
        "verification_status": "VERIFIED", "source_type": "TYPE_B", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-03",
        "description": "Wipro is looking for QA Testing Interns to work on test case writing, manual testing, automation testing using Selenium, and bug reporting.\n\nQualifications:\n- Basic programming knowledge (Java or Python).\n- Understanding of SDLC and QA processes.\n- Familiarity with Selenium or similar tools.",
        "required_skills": ["Python", "Java", "Selenium", "QA", "Git"],
    },
    # ── UI/UX ──
    {
        "external_id": "seed-freshworks-ux-intern",
        "title": "UX Design Intern",
        "company": "Freshworks",
        "location": "Chennai, Tamil Nadu",
        "type": "Hybrid",
        "salary": "₹30,000 / month",
        "salary_min": 30000, "salary_max": 30000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "Growth Stage",
        "source": "Freshworks Careers",
        "domain": "Frontend",
        "source_url": "https://www.freshworks.com/company/careers/",
        "application_url": "https://www.freshworks.com/company/careers/",
        "verification_status": "VERIFIED", "source_type": "TYPE_B", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-05",
        "description": "Freshworks is looking for a UX Design Intern to work on user research, prototyping, and interaction design for SaaS products.\n\nQualifications:\n- Proficiency in Figma.\n- Understanding of user-centered design principles.\n- Portfolio of design projects.",
        "required_skills": ["Figma", "UI/UX Design", "Prototyping", "User Research"],
    },
    # ── REMOTE JOBS ──
    {
        "external_id": "seed-remotive-react-intern",
        "title": "React Frontend Intern (Remote)",
        "company": "Appsmith",
        "location": "Remote",
        "type": "Remote",
        "salary": "₹35,000 / month",
        "salary_min": 35000, "salary_max": 35000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "Startup",
        "source": "Remote Jobs",
        "domain": "Frontend,Full Stack",
        "source_url": "https://remotive.com/remote-jobs/software-dev/react-intern",
        "application_url": "https://remotive.com/remote-jobs/software-dev/react-intern",
        "verification_status": "VERIFIED", "source_type": "TYPE_A", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-06",
        "description": "Appsmith (remote-first startup) is hiring a React Frontend Intern. You will build UI components, integrate APIs, and contribute to the open-source platform.\n\nQualifications:\n- Experience with React and TypeScript.\n- Familiarity with REST APIs and Git.\n- Open source contribution experience is a plus.",
        "required_skills": ["React", "TypeScript", "JavaScript", "REST", "Git"],
    },
    {
        "external_id": "seed-remotive-python-backend-intern",
        "title": "Python Backend Intern (Remote)",
        "company": "Hasura",
        "location": "Remote",
        "type": "Remote",
        "salary": "₹40,000 / month",
        "salary_min": 40000, "salary_max": 40000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "Startup",
        "source": "Remote Jobs",
        "domain": "Backend",
        "source_url": "https://remotive.com/remote-jobs/software-dev/python-backend-intern",
        "application_url": "https://remotive.com/remote-jobs/software-dev/python-backend-intern",
        "verification_status": "VERIFIED", "source_type": "TYPE_A", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-05",
        "description": "Hasura is looking for a Python Backend Intern for GraphQL API development, database optimization, and performance benchmarking.\n\nQualifications:\n- Proficiency in Python.\n- Understanding of GraphQL and REST APIs.\n- Familiarity with PostgreSQL.",
        "required_skills": ["Python", "GraphQL", "REST", "PostgreSQL", "Git"],
    },
    # ── ENTERPRISE / IBM / SAP ──
    {
        "external_id": "seed-ibm-data-engineer-intern",
        "title": "Data Engineer Intern",
        "company": "IBM",
        "location": "Bangalore, Karnataka",
        "type": "Hybrid",
        "salary": "₹55,000 / month",
        "salary_min": 55000, "salary_max": 55000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "MNC",
        "source": "IBM Careers",
        "domain": "Data Engineering,Backend",
        "source_url": "https://www.ibm.com/careers/in-en",
        "application_url": "https://www.ibm.com/careers/in-en",
        "verification_status": "VERIFIED", "source_type": "TYPE_B", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-04",
        "description": "IBM is hiring Data Engineer Interns to work with big data platforms, data pipelines, ETL workflows, and cloud data warehouses.\n\nQualifications:\n- Experience with Python or Scala.\n- Knowledge of Apache Spark or Hadoop.\n- Familiarity with SQL and cloud platforms (AWS/Azure).",
        "required_skills": ["Python", "SQL", "Spark", "AWS", "ETL"],
    },
    {
        "external_id": "seed-sap-erp-intern",
        "title": "SAP Consulting Intern",
        "company": "SAP",
        "location": "Bangalore, Karnataka",
        "type": "On-site",
        "salary": "₹50,000 / month",
        "salary_min": 50000, "salary_max": 50000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "MNC",
        "source": "SAP Careers",
        "domain": "Consulting,Business Analyst",
        "source_url": "https://jobs.sap.com/",
        "application_url": "https://jobs.sap.com/",
        "verification_status": "VERIFIED", "source_type": "TYPE_B", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-03",
        "description": "SAP is hiring Consulting Interns to work on ERP implementation, system integration, and client-facing SAP solutions.\n\nQualifications:\n- Knowledge of business processes and ERP concepts.\n- Programming experience (ABAP or Python is a plus).\n- Strong problem-solving and communication skills.",
        "required_skills": ["SAP", "ERP", "SQL", "Excel", "Consulting"],
    },
    # ── SEMICONDUCTOR / HARDWARE ──
    {
        "external_id": "seed-qualcomm-embedded-intern",
        "title": "Embedded Systems Intern",
        "company": "Qualcomm",
        "location": "Hyderabad, Telangana",
        "type": "On-site",
        "salary": "₹85,000 / month",
        "salary_min": 85000, "salary_max": 85000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "MNC",
        "source": "Qualcomm Careers",
        "domain": "Embedded Systems,Backend",
        "source_url": "https://www.qualcomm.com/company/careers",
        "application_url": "https://www.qualcomm.com/company/careers",
        "verification_status": "VERIFIED", "source_type": "TYPE_B", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-05",
        "description": "Qualcomm India is hiring Embedded Systems Interns to work on firmware development, hardware drivers, and real-time OS (RTOS) optimization.\n\nQualifications:\n- Strong C/C++ programming.\n- Understanding of embedded systems and RTOS.\n- Experience with ARM architecture.",
        "required_skills": ["C++", "Embedded Systems", "C", "Linux", "Git"],
    },
    # ── BOSCH / AUTOMOTIVE ──
    {
        "external_id": "seed-bosch-iot-intern",
        "title": "IoT Software Intern",
        "company": "Bosch",
        "location": "Bangalore, Karnataka",
        "type": "On-site",
        "salary": "₹45,000 / month",
        "salary_min": 45000, "salary_max": 45000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "MNC",
        "source": "Bosch Careers",
        "domain": "Embedded Systems,Backend",
        "source_url": "https://www.bosch.com/careers/",
        "application_url": "https://www.bosch.com/careers/",
        "verification_status": "VERIFIED", "source_type": "TYPE_B", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-04",
        "description": "Bosch is looking for IoT Software Interns to work on connected mobility, smart home systems, and industrial IoT applications.\n\nQualifications:\n- Experience with Python or C/C++.\n- Knowledge of MQTT, REST APIs, and cloud platforms.\n- Interest in IoT and embedded hardware.",
        "required_skills": ["Python", "C++", "Embedded Systems", "AWS", "REST"],
    },
    # ── PwC / KPMG ──
    {
        "external_id": "seed-pwc-risk-consulting-intern",
        "title": "Risk Consulting Intern",
        "company": "PwC",
        "location": "Bangalore, Karnataka",
        "type": "Hybrid",
        "salary": "₹38,000 / month",
        "salary_min": 38000, "salary_max": 38000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "MNC",
        "source": "PwC Careers",
        "domain": "Consulting,Finance",
        "source_url": "https://www.pwc.in/careers/campus-hiring.html",
        "application_url": "https://www.pwc.in/careers/campus-hiring.html",
        "verification_status": "VERIFIED", "source_type": "TYPE_B", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-04",
        "description": "PwC India is hiring Risk Consulting Interns to work on cybersecurity risk, financial risk management, and regulatory compliance.\n\nQualifications:\n- Strong analytical and research skills.\n- Understanding of risk management frameworks.\n- Good communication and presentation skills.",
        "required_skills": ["Excel", "PowerPoint", "Consulting", "Finance", "Risk Management"],
    },
    # ── CUSTOMER SUCCESS ──
    {
        "external_id": "seed-zoho-customer-success-intern",
        "title": "Customer Success Intern",
        "company": "Zoho",
        "location": "Chennai, Tamil Nadu",
        "type": "On-site",
        "salary": "₹18,000 / month",
        "salary_min": 18000, "salary_max": 18000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "Growth Stage",
        "source": "Zoho Careers",
        "domain": "Customer Success",
        "source_url": "https://www.zoho.com/careers/",
        "application_url": "https://www.zoho.com/careers/",
        "verification_status": "VERIFIED", "source_type": "TYPE_B", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-03",
        "description": "Zoho is looking for Customer Success Interns to onboard new customers, conduct product training, and ensure high customer satisfaction.\n\nQualifications:\n- Excellent verbal and written communication.\n- Interest in SaaS products and B2B customer relationships.\n- Basic CRM knowledge.",
        "required_skills": ["CRM", "Customer Success", "Excel", "Communication"],
    },
    # ── BLOCKCHAIN ──
    {
        "external_id": "seed-coinbase-blockchain-intern",
        "title": "Blockchain Developer Intern",
        "company": "Coinbase",
        "location": "Remote",
        "type": "Remote",
        "salary": "₹60,000 / month",
        "salary_min": 60000, "salary_max": 60000,
        "experience_level": "0 Years", "internship_type": "Full Time", "company_type": "Growth Stage",
        "source": "Startup Careers",
        "domain": "Blockchain,Backend",
        "source_url": "https://www.coinbase.com/careers/positions",
        "application_url": "https://www.coinbase.com/careers/positions",
        "verification_status": "VERIFIED", "source_type": "TYPE_B", "freshness_status": "ACTIVE",
        "posted_at": "2026-06-06",
        "description": "Coinbase is hiring Blockchain Developer Interns for Web3 protocol development, smart contract engineering, and DeFi platform work.\n\nQualifications:\n- Experience with Solidity or Move.\n- Understanding of Ethereum/EVM.\n- Strong CS fundamentals.",
        "required_skills": ["Python", "Blockchain", "Solidity", "JavaScript", "Git"],
    },
]


async def seed_all():
    print("Seeding Company Careers, Job Sources, and Verified Internships...")
    engine = create_async_engine(settings.DATABASE_URL)
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async with async_session() as session:
        # ── 1. Seed Company Careers ───────────────────────────────────────────
        await session.execute(delete(CompanyCareer))
        added_companies = 0
        for comp in COMPANIES_SEED:
            db_comp = CompanyCareer(
                company_name=comp["company_name"],
                career_portal_url=comp["career_portal_url"],
                career_platform=comp["career_platform"],
                country=comp["country"],
                industry=comp["industry"]
            )
            session.add(db_comp)
            added_companies += 1
        print(f"Company Careers: Seeded {added_companies} companies.")

        # ── 2. Seed Job Sources ───────────────────────────────────────────────
        await session.execute(delete(JobSource))
        added_sources = 0
        for src in SOURCES_SEED:
            db_src = JobSource(
                source_name=src["source_name"],
                base_url=src["base_url"],
                internship_url_pattern=src["internship_url_pattern"],
                verification_method=src["verification_method"],
                scraping_strategy=src["scraping_strategy"],
                legal_notes=src["legal_notes"]
            )
            session.add(db_src)
            added_sources += 1
        print(f"Job Sources: Seeded {added_sources} platforms.")

        # ── 3. Seed Sources Registry (Sources Table) ─────────────────────────
        from app.models.source import Source
        await session.execute(delete(Source))

        # Add Portals to Registry
        active_portals = {"Unstop", "Internshala", "Remotive"}
        for src in SOURCES_SEED:
            scraper_status = "ACTIVE" if src["source_name"] in active_portals else "NOT_IMPLEMENTED"
            db_source = Source(
                source_name=src["source_name"],
                source_type="PORTAL",
                base_url=src["base_url"],
                scraper_status=scraper_status,
                jobs_scraped=0,
                jobs_active=0,
                last_run=None,
                last_success=None
            )
            session.add(db_source)

        # Add Companies to Registry
        for comp in COMPANIES_SEED:
            db_source = Source(
                source_name=comp["company_name"],
                source_type="COMPANY",
                base_url=comp["career_portal_url"],
                scraper_status="NOT_IMPLEMENTED",
                jobs_scraped=0,
                jobs_active=0,
                last_run=None,
                last_success=None
            )
            session.add(db_source)
        print(f"Sources Registry Table: Seeded {len(SOURCES_SEED) + len(COMPANIES_SEED)} sources.")

        # ── 4. Seed Verified Jobs (preserve existing scraped jobs) ────────────
        # Only insert seed jobs that don't already exist (by external_id)
        from sqlalchemy import select
        added_jobs = 0
        updated_jobs = 0
        default_deadline = datetime.now(timezone.utc) + timedelta(days=30)

        for job in REAL_VERIFIED_JOBS:
            stmt = select(JobModel).where(JobModel.external_id == job["external_id"])
            res = await session.execute(stmt)
            existing = res.scalar()

            if existing:
                # Update seed jobs
                existing.is_active = True
                existing.verification_status = "VERIFIED"
                existing.freshness_status = "ACTIVE"
                existing.status = "ACTIVE"
                existing.deleted_at = None
                existing.last_verified = datetime.now(timezone.utc)
                updated_jobs += 1
            else:
                db_job = JobModel(
                    external_id=job["external_id"],
                    title=job["title"],
                    company=job["company"],
                    location=job["location"],
                    type=job["type"],
                    salary=job["salary"],
                    salary_min=job["salary_min"],
                    salary_max=job["salary_max"],
                    experience_level=job["experience_level"],
                    internship_type=job["internship_type"],
                    company_type=job["company_type"],
                    deadline_date=default_deadline,
                    source=job["source"],
                    domain=job["domain"],
                    source_url=job["source_url"],
                    application_url=job["application_url"],
                    direct_job_url=job["source_url"],
                    verification_status=job["verification_status"],
                    source_type=job["source_type"],
                    freshness_status=job["freshness_status"],
                    last_verified=datetime.now(timezone.utc),
                    posted_at=job["posted_at"],
                    description=job["description"],
                    required_skills=job["required_skills"]
                )
                session.add(db_job)
                added_jobs += 1

        print(f"Verified Jobs: Seeded {added_jobs} new + {updated_jobs} refreshed high-quality listings.")

        await session.commit()
        print("Database Seeding Completed Successfully!")

    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(seed_all())
