"""add_recommendations_and_signals

Revision ID: 9fef72545922
Revises: 9fd229d41af8
Create Date: 2026-06-11 10:53:14.152002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fef72545922'
down_revision: Union[str, None] = '9fd229d41af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('career_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('user_profiles', sa.Column('soft_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('user_profiles', sa.Column('experience_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('user_profiles', sa.Column('achievement_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    
    op.alter_column('user_profiles', 'career_recommendations', server_default=None)
    op.alter_column('user_profiles', 'soft_skills', server_default=None)
    op.alter_column('user_profiles', 'experience_signals', server_default=None)
    op.alter_column('user_profiles', 'achievement_signals', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'achievement_signals')
    op.drop_column('user_profiles', 'experience_signals')
    op.drop_column('user_profiles', 'soft_skills')
    op.drop_column('user_profiles', 'career_recommendations')
    # ### end Alembic commands ###
