"""add links to resume profiles

Revision ID: a4c66ca35d83
Revises: 85cac9cebf62
Create Date: 2026-06-07 23:45:36.226275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4c66ca35d83'
down_revision: Union[str, None] = '85cac9cebf62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_profiles', sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_profiles', 'links')
    # ### end Alembic commands ###
