"""add_scraper_metrics_and_direct_url_last_verified

Revision ID: ade6ebf73d4d
Revises: ade6385cc20f
Create Date: 2026-06-09 11:34:43.229102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade6ebf73d4d'
down_revision: Union[str, None] = 'ade6385cc20f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('jobs_found', sa.Integer(), nullable=False),
    sa.Column('jobs_parsed', sa.Integer(), nullable=False),
    sa.Column('jobs_saved', sa.Integer(), nullable=False),
    sa.Column('jobs_rejected', sa.Integer(), nullable=False),
    sa.Column('failure_rate', sa.Float(), nullable=False),
    sa.Column('last_scrape_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraper_metrics_id'), 'scraper_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_scraper_metrics_source_name'), 'scraper_metrics', ['source_name'], unique=True)
    op.add_column('jobs', sa.Column('direct_job_url', sa.Text(), nullable=True))
    op.execute("UPDATE jobs SET direct_job_url = source_url WHERE direct_job_url IS NULL")
    op.alter_column('jobs', 'direct_job_url', nullable=False)
    op.add_column('jobs', sa.Column('last_verified', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'last_verified')
    op.drop_column('jobs', 'direct_job_url')
    op.drop_index(op.f('ix_scraper_metrics_source_name'), table_name='scraper_metrics')
    op.drop_index(op.f('ix_scraper_metrics_id'), table_name='scraper_metrics')
    op.drop_table('scraper_metrics')
    # ### end Alembic commands ###
