"""add_security_and_verifications

Revision ID: ade6385cc20f
Revises: a4c66ca35d83
Create Date: 2026-06-09 11:12:00.324536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade6385cc20f'
down_revision: Union[str, None] = 'a4c66ca35d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_careers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('career_portal_url', sa.String(length=512), nullable=False),
    sa.Column('career_platform', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_careers_company_name'), 'company_careers', ['company_name'], unique=True)
    op.create_index(op.f('ix_company_careers_id'), 'company_careers', ['id'], unique=False)
    op.create_table('job_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('internship_url_pattern', sa.String(length=255), nullable=False),
    sa.Column('verification_method', sa.String(length=255), nullable=False),
    sa.Column('scraping_strategy', sa.String(length=255), nullable=False),
    sa.Column('legal_notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_sources_id'), 'job_sources', ['id'], unique=False)
    op.create_index(op.f('ix_job_sources_source_name'), 'job_sources', ['source_name'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.add_column('jobs', sa.Column('application_url', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('verification_status', sa.String(length=50), nullable=False, server_default='VERIFIED'))
    op.add_column('jobs', sa.Column('source_type', sa.String(length=50), nullable=False, server_default='TYPE_A'))
    op.add_column('jobs', sa.Column('freshness_status', sa.String(length=50), nullable=False, server_default='ACTIVE'))
    
    # Copy source_url to application_url for existing jobs
    op.execute("UPDATE jobs SET application_url = source_url WHERE application_url IS NULL")
    
    # Make application_url non-nullable
    op.alter_column('jobs', 'application_url', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'freshness_status')
    op.drop_column('jobs', 'source_type')
    op.drop_column('jobs', 'verification_status')
    op.drop_column('jobs', 'application_url')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_job_sources_source_name'), table_name='job_sources')
    op.drop_index(op.f('ix_job_sources_id'), table_name='job_sources')
    op.drop_table('job_sources')
    op.drop_index(op.f('ix_company_careers_id'), table_name='company_careers')
    op.drop_index(op.f('ix_company_careers_company_name'), table_name='company_careers')
    op.drop_table('company_careers')
    # ### end Alembic commands ###
