"""add_soft_delete_and_scraper_runtime_metrics

Revision ID: bd3968aefd7d
Revises: ade6ebf73d4d
Create Date: 2026-06-09 11:44:38.091815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd3968aefd7d'
down_revision: Union[str, None] = 'ade6ebf73d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('status', sa.String(length=50), nullable=True))
    op.execute("UPDATE jobs SET status = 'ACTIVE' WHERE status IS NULL")
    op.alter_column('jobs', 'status', nullable=False)

    op.add_column('jobs', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE jobs SET is_active = true WHERE is_active IS NULL")
    op.alter_column('jobs', 'is_active', nullable=False)

    op.add_column('jobs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    op.add_column('scraper_metrics', sa.Column('last_run', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scraper_metrics', sa.Column('runtime', sa.Float(), nullable=True))
    op.execute("UPDATE scraper_metrics SET runtime = 0.0 WHERE runtime IS NULL")
    op.alter_column('scraper_metrics', 'runtime', nullable=False)

    op.add_column('scraper_metrics', sa.Column('success_rate', sa.Float(), nullable=True))
    op.execute("UPDATE scraper_metrics SET success_rate = 0.0 WHERE success_rate IS NULL")
    op.alter_column('scraper_metrics', 'success_rate', nullable=False)
    
    op.drop_column('scraper_metrics', 'last_scrape_time')
    op.drop_column('scraper_metrics', 'failure_rate')
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraper_metrics', sa.Column('failure_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('scraper_metrics', sa.Column('last_scrape_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('scraper_metrics', 'success_rate')
    op.drop_column('scraper_metrics', 'runtime')
    op.drop_column('scraper_metrics', 'last_run')
    op.drop_column('jobs', 'deleted_at')
    op.drop_column('jobs', 'is_active')
    op.drop_column('jobs', 'status')
    # ### end Alembic commands ###
