"""create_sources_registry_and_job_filters

Revision ID: ef1635e5e1f0
Revises: bd3968aefd7d
Create Date: 2026-06-09 12:14:00.254703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1635e5e1f0'
down_revision: Union[str, None] = 'bd3968aefd7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('scraper_status', sa.String(length=50), nullable=False),
    sa.Column('jobs_scraped', sa.Integer(), nullable=False),
    sa.Column('jobs_active', sa.Integer(), nullable=False),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.create_index(op.f('ix_sources_source_name'), 'sources', ['source_name'], unique=True)
    op.add_column('jobs', sa.Column('salary_min', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('salary_max', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('experience_level', sa.String(length=50), server_default='0 Years', nullable=False))
    op.add_column('jobs', sa.Column('internship_type', sa.String(length=50), server_default='Full Time', nullable=False))
    op.add_column('jobs', sa.Column('company_type', sa.String(length=50), server_default='Growth Stage', nullable=False))
    op.add_column('jobs', sa.Column('deadline_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('jobs', 'domain',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'domain',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('jobs', 'deadline_date')
    op.drop_column('jobs', 'company_type')
    op.drop_column('jobs', 'internship_type')
    op.drop_column('jobs', 'experience_level')
    op.drop_column('jobs', 'salary_max')
    op.drop_column('jobs', 'salary_min')
    op.drop_index(op.f('ix_sources_source_name'), table_name='sources')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
